### ISSUE TITLE
Value Assignment Bug in Arrays

### ISSUE THREAD

**Issue by nourazzi8** [jaamsim/jaamsim#11]
The AttributeAssignmentList in the Assign Object will not accept an array as input when given two or more indices, it will only accept a single index on its left-hand side.

For example:
AttributeDefinitionList :  V '{ { {0,1}, {2,3} },{ {4,5}, {6,7} } }'
AttributeAssignmentList : {' this.V(1)(1) = {8, 9} '}

The input in the AttributeAssignmentList in the example above will not be accepted, however it will be taken in the example below:

AttributeDefinitionList :  { V '{ { {0,1}, {2,3} },{ {4,5}, {6,7} } }' } { i 0 }
AttributeAssignmentList : {'this.i = this.V(1)(1) '}

Google Group Thread: https://groups.google.com/forum/#!topic/jaamsim-users/LTuXnvJuRPw

**Comment by hharrison** [comment]
The following bug was introduced in -07 that has just been fixed in -08. 

"Bug fix to Priority and Match inputs for EntityContainer.  An expression containing 'this.obj' now works correctly when it is entered to the Priority and Match inputs to an EntityContainer.  This bug was introduced accidentally in release 2018-07."

**Comment by hharrison** [comment]
My apologies, this is actually a separate issue in that multi-dimensional indices are not yet supported in this case. Will leave this issue open until this functionality is added.

**Comment by dharryking** [comment]
This enhancement was added in release 2019-04:

Multi-index assignment. An element of a multi-index array can now be set using the Assign object. For example, the AttributeAssignmentList keyword can now accept the following type of input ‘this.attrib(2)(3) = 5’, where the attribute ‘attrib’ is a two index array. Formerly, assignment was restricted to a single index array. Note that each index in the assignment input can be replaced by an expression that returns a number. Furthermore, the object on the left hand side prior to the dot (“.”) can be replaced by an expression that returns a object.
