### ISSUE TITLE
JS 2018-08 : InputValue disappearing from View

### ISSUE THREAD

**Issue by renaudlr** [jaamsim/jaamsim#12]
Hi,

From version 2018-08, InputValue obects disappear from model view after changing focus. This is new to version 2018-08.

To reproduce:
- create a blank model
- drop an InputValue anywhare
- change selection and see the InputValue object that disappears.

The object is nevertheless visible in the 'Object Selector' window.

Best regards,

**Comment by hharrison** [comment]
Fixed in commit 5eb7a0f902486b172f04ba17961e586e7df2e3b6 which will be included in the next release. Thanks for reporting the issue!
