### ISSUE TITLE
Entity losses when two Pack objects share the same Queue

### ISSUE THREAD

**Issue by renaudlr** [jaamsim/jaamsim#13]
Hi,

When two Pack objects work in parallel using the same Queue, the first Pack that terminates its job clears the Queue, no matter whether other entities in the Queue belong to the other Pack, resulting in an unexpected behaviour with entity losses.
This seems to happen no matter whether the entities or container are of the same type.
The attached model makes it possible to reproduce using JS 2018-07 or 2018-08.

Best regards,

Renaud
[Test_model_entity_losses.zip](https://github.com/jaamsim/jaamsim/files/2695530/Test_model_entity_losses.zip)

**Comment by hharrison** [comment]
Closing as this appears to be a configuration issue, please continue this discussion on the jaamsim user forum if any further clarification arises.

**Comment by renaudlr** [comment]
Ok, got it. Thank you for the clarification.
