### ISSUE TITLE
Pack in a SubModel causes an error on entity name

### ISSUE THREAD

**Issue by renaudlr** [jaamsim/jaamsim#19]
Can be reproduced with the attached model with releases 2020-07 and 2020-08 :

EXCEPTION AT TIME: 0,000000 s
An entity name cannot be blank or contain spaces, tabs, braces, single or double quotes, square brackets, the hash character, or a period.
 Name: SubModel1.Pack_1
Thrown exception call stack:
com.jaamsim.input.InputAgent.generateEntityWithName(InputAgent.java:317)
com.jaamsim.input.InputAgent.generateEntityWithName(InputAgent.java:298)
com.jaamsim.ProcessFlow.Pack.getNextContainer(Pack.java:117)
com.jaamsim.ProcessFlow.Pack.startProcessing(Pack.java:136)
com.jaamsim.ProcessFlow.Device.startStep(Device.java:172)
com.jaamsim.ProcessFlow.Device.restart(Device.java:122)
com.jaamsim.ProcessFlow.LinkedService.queueChanged(LinkedService.java:212)
com.jaamsim.ProcessFlow.Queue$DoQueueChanged.process(Queue.java:236)
com.jaamsim.events.EventManager.executeTarget(EventManager.java:172)
com.jaamsim.events.EventManager.execute(EventManager.java:257)
com.jaamsim.events.Process.run(Process.java:101)
[Test Pack SubModel.zip](https://github.com/jaamsim/jaamsim/files/4767518/Test.Pack.SubModel.zip)

**Comment by hharrison** [comment]
I believe this was fixed in version 2020-10, please confirm if it is still a problem for you.

**Comment by renaudlr** [comment]
The issue has actually been fixed in release 2020-11. Thank you!
