### ISSUE TITLE
Not starts on Ubuntu 18.04

### ISSUE THREAD

**Issue by ricardojlrufino** [jaamsim/jaamsim#20]
i965: Failed to submit batchbuffer: Arquivo ou diretório inexistente

Fail in try render, central part of window...
JaamSim2020-09.jar

**Comment by ricardojlrufino** [comment]
glxgears, working...

**Comment by hharrison** [comment]
It is related to a bug in the integrated Intel GPU driver that won't be fixed, you can run with software only rendering on this machine by starting jaamsim this way:

export LIBGL_ALWAYS_SOFTWARE=1
java -jar JaamSim2020-09.jar

Asking questions on the jaamsim user forum will get you faster response in the future.
