### ISSUE TITLE
issue about the nextProcess field in Process class

### ISSUE THREAD

**Issue by zhanyeye** [jaamsim/jaamsim#21]
I read the code of the `Process` class and `EventManager` class carefully, but I still don’t understand the `nextProcess` field in the `Process` class.
https://github.com/jaamsim/jaamsim/blob/cabbfaff38e872a73c31825921984d56a47cb3fd/src/main/java/com/jaamsim/events/Process.java#L42-L44
Excuse me, Why does Process class need the `nextProcess` field? Thank you

**Comment by hharrison** [comment]
This is related to how the startProcess() API is implemented, as sub-processes are started, the original process is paused until the subprocess either waits, or exists. Upon waiting or exiting, the subprocess notifies whoever started it to continue execution, the nextProcess filed is used to hold this reference.

These kind of questions are better asked on the jaamsim forum, please ask them there in the future.

**Comment by zhanyeye** [comment]
Thank you for the reply, I now have a better understanding of the `nextProcess`.
Thanks for your reminder, I will ask questions on the JaamSim forum in the future
