### ISSUE TITLE
Renaming a label to an already used name throws an error but is incorrectly resolved.

### ISSUE THREAD

**Issue by Wolgo** [jaamsim/jaamsim#22]
When you rename a label to a previously used name it correctly throws an error message and changes the text of the label back. It however still changes the name of the connected entity, causing an internal naming inconsistency. 

My diagnosis is focused on the EntityLabel : 
```
	@Override
	public void acceptEdits() {
		GUIListener gui = getJaamSimModel().getGUIListener();
		if (gui == null)
			return;
		try {
			// Rename both the target entity and the label
			gui.renameEntity(targetEntity.getValue(), getText());
			super.acceptEdits();
		}
		catch (ErrorException e) {
			super.cancelEdits();
			gui.invokeErrorDialogBox("Input Error", e.getMessage());
		}
	}
```

I think the lines:
```
			gui.renameEntity(targetEntity.getValue(), getText());
			super.acceptEdits();
```
Should become:
```
			super.acceptEdits();
			gui.renameEntity(targetEntity.getValue(), getText());
```
I expect that it will now correctly first check if the name is already used, and then change the entity name.
Sadly I don't have the time to figure out how the AntBuildTool works to check this behaviour.

**Comment by dharryking** [comment]
Thank you for reporting this bug. It has been fixed by commit fc63d581980fa51a26122232875fb6c7fa78d769 (JS: check for name collision is GUIFrame.renameEntity). This bug fix has been included in release 2020-12.

Harry
