### ISSUE TITLE
Incompatibility between jaamsim files from linux to windows

### ISSUE THREAD

**Issue by leo-smi** [jaamsim/jaamsim#30]
The file generate on linux doesn't work properly on windows 10, I didn't try the opposite because my windows do not support openGL needed.

**Comment by dharryking** [comment]
Please provide the file you created under Linux so we can see what is going on.

**Comment by leo-smi** [comment]
https://drive.google.com/file/d/1v9nNvJwE5Sxuk574M7yLesNTBEuaLPyZ/view?usp=share_link

**Comment by dharryking** [comment]
Your file opened correctly under JaamSim 2022-06 on a Windows 10 computer. It also works correctly under earlier versions of JaamSim. This may be a problem with your Windows computer's ability to run JaamSim. Try running the models under Help > Examples as a test of the installation. If you need more help, please continue this discussion by posting on the JaamSim form which is available on the jaamsim.com website.
