### ISSUE TITLE
Bug 1426 - OpenGL intialization gives fatal error on some Linux distributions

### ISSUE THREAD

**Issue by descendingnerdliness** [jaamsim/jaamsim#31]
I seem to be suffering this bug on my ATI Radeon TURKS video. The problem has been fixed in jogl 2.4.0, But I believe that must be added to the jar. I would be happy to roll my own if I could get some instructions. Perhaps someone could give me those.
Thanks

**Comment by dharryking** [comment]
Does this bug occur under release 2022-06?  TURKS is a very old graphics card -- have you updated the driver?

**Comment by dharryking** [comment]
If you need any more help, please continue this discussion on the JaamSim forum which you can find on the jaamsim.com website.
