### ISSUE TITLE
Version The version issue

### ISSUE THREAD

**Issue by Bigbang666** [jaamsim/jaamsim#35]
Hello sir, I followed the programming manual provided by JaamSim and installed Eclipse 5.2.1 and JDK 11. I downloaded the JaamSim files from GitHub and configured them accordingly. However, I'm still encountering errors. Could you please advise if I should install a different version? If this is not the issue, do you have any suggestions?

**Comment by hharrison** [comment]
You'll have to provide some more context on what error you are seeing. The specific version of eclipse is not particularly important, and a java version of 8 or higher is all that should be required.

**Comment by hharrison** [comment]
Needinfo.
