### ISSUE TITLE
When editing labels in the View window, pressing SHIFT results in a square character

### ISSUE THREAD

**Issue by nelsonuhan** [jaamsim/jaamsim#4]
It looks like this:

![screen shot 2017-07-18 at 11 44 16](https://user-images.githubusercontent.com/7253603/28326353-86649d92-6bae-11e7-81ab-a18ba100bca8.png)

Some system information:

* JaamSim 2017-07
* macOS 10.12.5
* Java 8 Update 131

Please let me know if you need any more information.

**Comment by dharryking** [comment]
Fixed by commit 9308795a8188a97abc63e4834c74c82a6bd09df2
Included in release 2017-09
