### ISSUE TITLE
Object placement incorrect when dragging-and-dropping

### ISSUE THREAD

**Issue by nelsonuhan** [jaamsim/jaamsim#5]
Here is an example:

![dragdrop](https://user-images.githubusercontent.com/7253603/28329007-4c8cc330-6bb6-11e7-9acf-65f03ce78080.gif)

Some system information:

* JaamSim 2017-07
* macOS 10.12.5
* Java 8 Update 131

Please let me know if you need any more information.

**Comment by dharryking** [comment]
Fixed by commit 39c6d2ac8be694addbd4430636d90108b7701bd3
Included in release 2017-09
