### ISSUE TITLE
NullPointerExceptions when using FileToVector

### ISSUE THREAD

**Issue by wf-r** [jaamsim/jaamsim#6]
Hi,
when using FileToVector, we encounter two types of NullPointerExceptions (see models attached below):

1. NullPointer on Execution
When using the output of FileToVector as input of e.g. a ConveyorEntity, we receive a NullPointerException on Execution of the simulation in the GUI. The simulation can be run by resetting it after the NullPointerException and starting it again (which reads the input file and then correctly starts the simulation). A start via command line is not possible.

2. NullPoiner on Startup
When using the output of FileToVector in an ExpressionEntity, which is itself used in the OpenCondition of an ExpressionThreshold, we receive a NullPointerException on Startup. The simulation can be run by starting it in the GUI (which yields a pop-up), then resetting it and starting it again (which reads the input file and then correctly starts the simulation). A start via command line is not possible.

[Bug.zip](https://github.com/jaamsim/jaamsim/files/1192801/Bug.zip)

**Comment by dharryking** [comment]
Item 1 is fixed by commit 62222700e990c6c5e196e6aac624afb0eb2067f4 
Item 2 is fixed by commit 7ea9046889517c7fc46ee5d6d0fe882c52716bb2
Both are included in release 2017-09

**Comment by wf-r** [comment]
Thanks
